# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)
admin=User.create(:email=>"admin@admin.pl",:password=>"zaq12wsxz",:password_confirmation=>"zaq12wsxz", :admin=>true,
:name=>"Admin", :address=>"Adminowa 3", :city=>"Adminowo", :postcode=>"66-666", :phone=>"666999666")
cyfra=Printtype.create({:name=>"Druk Cyfrowy"})
offset=Printtype.create({:name=>"Druk Offsetowy"})
sitodruk=Printtype.create({:name=>"Sitodruk"})
wielkof=Printtype.create({:name=>"Druk Wielkoformatowy"})
#cyfra+Sitodruk
Paper.create({:name=>"Papier Offsetowy 70g/m2", :price=>"0.09", :printtype_ids=>["1", "2","3"] })
Paper.create({:name=>"Papier Offsetowy 80g/m2", :price=>"0,1", :printtype_ids=>["1", "2","3"] })
Paper.create({:name=>"Papier Offsetowy 90g/m2", :price=>"", :printtype_ids=>["1", "2"] })
Paper.create({:name=>"Papier Kredowany 115g/m2", :price=>"0.16", :printtype_ids=>["1", "2","3"] })
Paper.create({:name=>"Papier Kredowany 130g/m2", :price=>"0.19", :printtype_ids=>["1", "2","3"] })
Paper.create({:name=>"Papier Kredowany 150g/m2", :price=>"", :printtype_ids=>["1", "2"] })
Paper.create({:name=>"Papier Kredowany 170g/m2", :price=>"0.20", :printtype_ids=>["1", "2","3"] })
Paper.create({:name=>"Papier Kredowany 200g/m2", :price=>"0.22", :printtype_ids=>["1", "2","3"] })
Paper.create({:name=>"Papier DCP Ivory 250g/m2", :price=>"0.70", :printtype_ids=>["1"] })
Paper.create({:name=>"Papier DCP Biały 280g/m2", :price=>"0.70", :printtype_ids=>["1"] })
Paper.create({:name=>"Folia Folex ", :price=>"6,8", :printtype_ids=>["1"] })
Paper.create({:name=>"Papier Samoprzylepny MACTAC", :price=>"1,6", :printtype_ids=>["1"] })
#Sitodruk
Paper.create({:name=>"Papier Samoprzylepny półbł. Biały", :price=>"0.60", :printtype_ids=>["2","3"] })
Paper.create({:name=>"Papier Samoprzylepny złoty", :price=>"", :printtype_ids=>["2","3"] })
Paper.create({:name=>"Papier Samoprzylepny kolor mat", :price=>"", :printtype_ids=>["2","3"] })
Paper.create({:name=>"Karton 350g (spód szary) ", :price=>"0.32", :printtype_ids=>["2","3"] })
Paper.create({:name=>"Karton 230g (spód szary) GD-2", :price=>"0.22", :printtype_ids=>["2","3"] })
Paper.create({:name=>"Tektura Introligatorska 1,5 mm", :price=>"0.75", :printtype_ids=>["2","3"] })
#Wielkoformatowe
Paper.create({:name=>"MAT COATED 120G", :price=>"24", :width=>"60", :printtype_ids=>["4"] })
Paper.create({:name=>"MAT COATED 120G", :price=>"40", :width=>"100", :printtype_ids=>["4"] })
Paper.create({:name=>"MAT COATED 180G", :price=>"30", :width=>"60", :printtype_ids=>["4"] })
Paper.create({:name=>"MAT COATED 180G", :price=>"50", :width=>"100", :printtype_ids=>["4"] })
Paper.create({:name=>"PHOTO GLOSSY 190G", :price=>"60", :width=>"60", :printtype_ids=>["4"] })
Paper.create({:name=>"PHOTO GLOSSY 190G", :price=>"100", :width=>"100", :printtype_ids=>["4"] })
Paper.create({:name=>"SAMOPRZYLEPNY  VINYL 270G", :price=>"125", :width=>"100", :printtype_ids=>["4"] })
Paper.create({:name=>"CANVAS (płótno)", :price=>"175", :width=>"100", :printtype_ids=>["4"] })
Paper.create({:name=>"CAD 90G (EKO)", :price=>"18", :width=>"60", :printtype_ids=>["4"] })
Paper.create({:name=>"CAD 90G (EKO)", :price=>"30", :width=>"100", :printtype_ids=>["4"] })
Paper.create({:name=>"CANON FOTO GLACIER (ze strukturą)", :price=>"75", :width=>"60", :printtype_ids=>["4"] })
Paper.create({:name=>"CANON FOTO GLACIER (ze strukturą)", :price=>"125", :width=>"100", :printtype_ids=>["4"] })
Paper.create({:name=>"FOLIA TWARDE PCV (SICO) WYDRUK ROLLUP", :price=>"75", :width=>"100", :printtype_ids=>["4"] })
#Opcje
Option.create({"price"=>"1", "name"=>"Bigowanie", "printtype_ids"=>["1", "2", "3"], "per_unit"=>"0"})
Option.create({"price"=>"1", "name"=>"Foliowanie", "printtype_ids"=>["1", "2", "3"], "per_unit"=>"0"})
Option.create({"price"=>"1", "name"=>"Bindowanie", "printtype_ids"=>["1", "2", "3"], "per_unit"=>"0"})
Option.create({"price"=>"1", "name"=>"Zszywanie", "printtype_ids"=>["1", "2", "3"], "per_unit"=>"0"})
Option.create({"price"=>"1", "name"=>"Klejenie", "printtype_ids"=>["1", "2", "3"], "per_unit"=>"0"})
Option.create({"price"=>"1", "name"=>"Klejenie", "printtype_ids"=>["2","3"], "per_unit"=>"0"})
Option.create({"price"=>"1", "name"=>"Lakierowanie", "printtype_ids"=>["2","3"], "per_unit"=>"0"})
Option.create({:name=>"Lakierowanie punktowe", :printtype_ids=>["2","3"],:price=>1, :per_unit=>false})
Option.create({"price"=>"1", "name"=>"Podklejenia", "printtype_ids"=>["3"], "per_unit"=>"0"})
Option.create({"price"=>"35", "name"=>"Laminowanie na zimno", "printtype_ids"=>["3"], "per_unit"=>"0"})
#Formats
Format.create({"name"=>"A3", "value"=>"1", "printtype_id"=>cyfra.id})
Format.create({"name"=>"A4", "value"=>"2", "printtype_id"=>cyfra.id})
Format.create({"name"=>"A5", "value"=>"4", "printtype_id"=>cyfra.id})
Format.create({"name"=>"A6", "value"=>"8", "printtype_id"=>cyfra.id})
Format.create({"name"=>"Wizytówki", "value"=>"16", "printtype_id"=>cyfra.id})
o_a2=Format.create({"name"=>"A2", "value"=>"1", "printtype_id"=>offset.id})
o_a3=Format.create({"name"=>"A3", "value"=>"2", "printtype_id"=>offset.id})
o_a4=Format.create({"name"=>"A4", "value"=>"3", "printtype_id"=>offset.id})
o_a5=Format.create({"name"=>"A5", "value"=>"4", "printtype_id"=>offset.id})
o_a6=Format.create({"name"=>"A6", "value"=>"5", "printtype_id"=>offset.id})
s_b1=Format.create({"name"=>"B1", "value"=>"1", "printtype_id"=>sitodruk.id})
s_a2=Format.create({"name"=>"A2", "value"=>"2", "printtype_id"=>sitodruk.id})
s_a3=Format.create({"name"=>"A3", "value"=>"3", "printtype_id"=>sitodruk.id})
s_a4=Format.create({"name"=>"A4", "value"=>"4", "printtype_id"=>sitodruk.id})
s_a5=Format.create({"name"=>"A5", "value"=>"5", "printtype_id"=>sitodruk.id})
s_a6=Format.create({"name"=>"A6", "value"=>"6", "printtype_id"=>sitodruk.id})
Format.create({"name"=>"100x200", "value"=>"100","width"=>"200", "printtype_id"=>wielkof.id})
Format.create({"name"=>"100x150", "value"=>"100","width"=>"150", "printtype_id"=>wielkof.id})
Format.create({"name"=>"100x120", "value"=>"100","width"=>"120", "printtype_id"=>wielkof.id})
Format.create({"name"=>"100x100", "value"=>"100","width"=>"100", "printtype_id"=>wielkof.id})
Format.create({"name"=>"100x70", "value"=>"100","width"=>"70", "printtype_id"=>wielkof.id})
Format.create({"name"=>"100x50", "value"=>"100","width"=>"50", "printtype_id"=>wielkof.id})
Format.create({"name"=>"60x120", "value"=>"60","width"=>"120", "printtype_id"=>wielkof.id})
Format.create({"name"=>"60x90", "value"=>"60","width"=>"90", "printtype_id"=>wielkof.id})
Format.create({"name"=>"60x60", "value"=>"60","width"=>"60", "printtype_id"=>wielkof.id})
Format.create({"name"=>"60x40", "value"=>"60","width"=>"40", "printtype_id"=>wielkof.id})
Format.create({"name"=>"Inny", "value"=>"1","width"=>"1", "printtype_id"=>wielkof.id})


#Prices
#cyfrowy
Price.create({"format_id"=>"", "bracket"=>"1", "color"=>"1", "value"=>"0.90", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10", "color"=>"1", "value"=>"0.90", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"50", "color"=>"1", "value"=>"0.78", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"100", "color"=>"1", "value"=>"0.78", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"250", "color"=>"1", "value"=>"0.48", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10000", "color"=>"1", "value"=>"0.48", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"1", "color"=>"2", "value"=>"1.80", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10", "color"=>"2", "value"=>"1.8", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"50", "color"=>"2", "value"=>"1.56", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"100", "color"=>"2", "value"=>"1.56", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"250", "color"=>"2", "value"=>"0.96", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10000", "color"=>"2", "value"=>"0.96", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"1", "color"=>"3", "value"=>"9.00", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10", "color"=>"3", "value"=>"4.60", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"50", "color"=>"3", "value"=>"2.90", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"100", "color"=>"3", "value"=>"2.50", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"250", "color"=>"3", "value"=>"2.25", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10000", "color"=>"3", "value"=>"2.05", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"1", "color"=>"4", "value"=>"10.80", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10", "color"=>"4", "value"=>"6.40", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"50", "color"=>"4", "value"=>"4.46", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"100", "color"=>"4", "value"=>"4.06", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"250", "color"=>"4", "value"=>"3.21", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10000", "color"=>"4", "value"=>"3.01", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"1", "color"=>"5", "value"=>"18.00", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10", "color"=>"5", "value"=>"9.10", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"50", "color"=>"5", "value"=>"5.65", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"100", "color"=>"5", "value"=>"4.90", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"250", "color"=>"5", "value"=>"4.40", "printtype_id"=>"1"})
Price.create({"format_id"=>"", "bracket"=>"10000", "color"=>"5", "value"=>"3.95", "printtype_id"=>"1"})
#offset
Price.create({"format_id"=>o_a2.id, "bracket"=>"1000", "color"=>"", "value"=>"0.25", "printtype_id"=>"2"})
Price.create({"format_id"=>o_a2.id, "bracket"=>"5000", "color"=>"", "value"=>"0", "printtype_id"=>"2"})
Price.create({"format_id"=>o_a3.id, "bracket"=>"1000", "color"=>"", "value"=>"0.15", "printtype_id"=>"2"})
Price.create({"format_id"=>o_a3.id, "bracket"=>"5000", "color"=>"", "value"=>"0.1", "printtype_id"=>"2"})
Price.create({"format_id"=>o_a4.id, "bracket"=>"1000", "color"=>"", "value"=>"0.1", "printtype_id"=>"2"})
Price.create({"format_id"=>o_a4.id, "bracket"=>"5000", "color"=>"", "value"=>"0.07", "printtype_id"=>"2"})
Price.create({"format_id"=>o_a5.id, "bracket"=>"1000", "color"=>"", "value"=>"0.1", "printtype_id"=>"2"})
Price.create({"format_id"=>o_a5.id, "bracket"=>"5000", "color"=>"", "value"=>"0", "printtype_id"=>"2"})
Price.create({"format_id"=>o_a6.id, "bracket"=>"1000", "color"=>"", "value"=>"0.1", "printtype_id"=>"2"})
Price.create({"format_id"=>o_a6.id, "bracket"=>"5000", "color"=>"", "value"=>"0", "printtype_id"=>"2"})
#sitodruk
Price.create({"format_id"=>s_b1.id, "bracket"=>"50000", "color"=>"", "value"=>"0.75", "printtype_id"=>"3"})
Price.create({"format_id"=>s_a2.id, "bracket"=>"50000", "color"=>"", "value"=>"0.75", "printtype_id"=>"3"})
Price.create({"format_id"=>s_a3.id, "bracket"=>"50000", "color"=>"", "value"=>"0.45", "printtype_id"=>"3"})
Price.create({"format_id"=>s_a4.id, "bracket"=>"50000", "color"=>"", "value"=>"0.3", "printtype_id"=>"3"})
Price.create({"format_id"=>s_a5.id, "bracket"=>"50000", "color"=>"", "value"=>"0.2", "printtype_id"=>"3"})
Price.create({"format_id"=>s_a6.id, "bracket"=>"50000", "color"=>"", "value"=>"0.2", "printtype_id"=>"3"})
